<?php
/*
 * Base class for all view actions.
 * Responsible for calling common events.
 */
class helpdeskViewAction extends waViewAction
{
    public function display($clear_assign = true)
    {
        $result = parent::display(false);

        // I salute you, o brave explorers who reached these depths of the source code
        // in your noble quest for ultimate knowledge! :D
        // As a reward for your great efforts, I present you this powerful, but kinda experimental plugin hook.
        // It's currently not included in official docs.

        // Plugins can add custom HTML (and therefore JS) at the end of output
        // generated by any view action.
        $params = array(
            'action' => $this,
            'view' => $this->view,
        );
        $plugin_blocks = wa('helpdesk')->event('view_action', $params);
        foreach($plugin_blocks as $html) {
            $result .= $html;
        }

        if ($clear_assign) {
            $this->view->clearAllAssign();
        }
        return $result;
    }
}

